AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvironmentName:
    Description: The name for the MWAA Airflow environment
    Type: String
  MaxWorkerNodes:
    Description: The maximum number of workers that can run in the environment
    Type: Number
    Default: 2
  DagProcessingLogs:
    Description: Log level for DagProcessing
    Type: String
    Default: INFO
  SchedulerLogsLevel:
    Description: Log level for SchedulerLogs
    Type: String
    Default: INFO
  TaskLogsLevel:
    Description: Log level for TaskLogs
    Type: String
    Default: INFO
  WorkerLogsLevel:
    Description: Log level for WorkerLogs
    Type: String
    Default: INFO
  WebserverLogsLevel:
    Description: Log level for WebserverLogs
    Type: String
    Default: INFO
  MwaaExecRoleName:
    Type: String
  MwaaManagedPolicyName:
    Type: String
    Default: MwaaManagedPolicy
    
Resources:
  MwaaEnvironment:
    Type: AWS::MWAA::Environment
    DependsOn: MwaaExecutionPolicy
    Properties:
      Name: !Ref EnvironmentName
      AirflowConfigurationOptions:
        core.default_ui_timezone: "Australia/Melbourne"
        logging.logging_level: INFO
        secrets.backend: "airflow.contrib.secrets.aws_secrets_manager.SecretsManagerBackend"
        secrets.backend_kwargs: "{\"connections_prefix\" : \"airflow/connections\", \"variables_prefix\" : \"airflow/variables\"}"
      DagS3Path: dags
      EnvironmentClass: mw1.small
      ExecutionRoleArn: !GetAtt MwaaExecutionRole.Arn
      RequirementsS3Path: requirements.txt
      WebserverAccessMode: PRIVATE_ONLY
      MaxWorkers: !Ref MaxWorkerNodes
      SourceBucketArn: !ImportValue MWAAEnvironmentS3BucketArn
      NetworkConfiguration:
        SecurityGroupIds:
          - !ImportValue MwaaSecurityGroupId
        SubnetIds:
          - !ImportValue MwaaPrivateSubnet1
          - !ImportValue MwaaPrivateSubnet2
      LoggingConfiguration:
        DagProcessingLogs:
          LogLevel: !Ref DagProcessingLogs
          Enabled: true
        SchedulerLogs:
          LogLevel: !Ref SchedulerLogsLevel
          Enabled: true
        TaskLogs:
          LogLevel: !Ref TaskLogsLevel
          Enabled: true
        WorkerLogs:
          LogLevel: !Ref WorkerLogsLevel
          Enabled: true
        WebserverLogs:
          LogLevel: !Ref WebserverLogsLevel
          Enabled: true

  MwaaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref MwaaExecRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - airflow-env.amazonaws.com
                - airflow.amazonaws.com
            Action:
             - "sts:AssumeRole"
      Path: "/service-role/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite

  MwaaExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    DependsOn: MwaaExecutionRole
    Properties:
      ManagedPolicyName: !Ref MwaaManagedPolicyName
      Roles:
        - !Ref MwaaExecutionRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: airflow:PublishMetrics
            Resource:
              - !Sub "arn:aws:airflow:${AWS::Region}:${AWS::AccountId}:environment/${EnvironmentName}"
          - Effect: Deny
            Action: s3:ListAllMyBuckets
            Resource:
              - !ImportValue MWAAEnvironmentS3BucketArn
              - !Sub
                - '${BucketName}/*'
                - BucketName: !ImportValue MWAAEnvironmentS3BucketArn
          - Effect: Allow
            Action:
              - "s3:GetObject*"
              - "s3:GetBucket*"
              - "s3:List*"
            Resource:
              - !ImportValue MWAAEnvironmentS3BucketArn
              - !Sub
                - '${BucketName}/*'
                - BucketName: !ImportValue MWAAEnvironmentS3BucketArn
          - Effect: Allow
            Action:
              - logs:DescribeLogGroups
            Resource: "*"

          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:CreateLogGroup
              - logs:PutLogEvents
              - logs:GetLogEvents
              - logs:GetLogRecord
              - logs:GetLogGroupFields
              - logs:GetQueryResults
              - logs:DescribeLogGroups
            Resource:
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:airflow-${AWS::StackName}*"
          - Effect: Allow
            Action: cloudwatch:PutMetricData
            Resource: "*"
          - Effect: Allow
            Action:
              - sqs:ChangeMessageVisibility
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ReceiveMessage
              - sqs:SendMessage
            Resource:
              - !Sub "arn:aws:sqs:${AWS::Region}:*:airflow-celery-*"
          - Effect: Allow
            Action:
              - kms:Decrypt
              - kms:DescribeKey
              - "kms:GenerateDataKey*"
              - kms:Encrypt
            NotResource: !Sub "arn:aws:kms:*:${AWS::AccountId}:key/*"
            Condition:
              StringLike:
                "kms:ViaService":
                  - !Sub "sqs.${AWS::Region}.amazonaws.com"

Outputs:
  MwaaApacheAirflowUI:
    Description: MWAA Environment Webserver URL
    Value: !Sub  "https://${MwaaEnvironment.WebserverUrl}"
    