AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
  MaxWorkerNodes:
    Description: The maximum number of workers that can run in the environment
    Type: Number
    Default: 2
  DagProcessingLogs:
    Description: Log level for DagProcessing
    Type: String
    Default: INFO
  SchedulerLogsLevel:
    Description: Log level for SchedulerLogs
    Type: String
    Default: INFO
  TaskLogsLevel:
    Description: Log level for TaskLogs
    Type: String
    Default: INFO
  WorkerLogsLevel:
    Description: Log level for WorkerLogs
    Type: String
    Default: INFO
  WebserverLogsLevel:
    Description: Log level for WebserverLogs
    Type: String
    Default: INFO

Resources:
  MwaaEnvironment:
    Type: AWS::MWAA::Environment
    Properties:
      Name: !Ref EnvironmentName
      AirflowConfigurationOptions:
        core.default_ui_timezone: "Australia/Melbourne"
        logging.logging_level: INFO
        secrets.backend: "airflow.contrib.secrets.aws_secrets_manager.SecretsManagerBackend"
        secrets.backend_kwargs: "{\"connections_prefix\" : \"airflow/connections\", \"variables_prefix\" : \"airflow/variables\"}"
      SourceBucketArn: !ImportValue MWAAEnvironmentS3BucketArn
      ExecutionRoleArn: !ImportValue MwaaExecutionRoleArn
      DagS3Path: dags
      PluginsS3Path: plugins.zip
      RequirementsS3Path: requirements.txt
      NetworkConfiguration:
        SecurityGroupIds:
          - !ImportValue MwaaSecurityGroupId
        SubnetIds:
          - !ImportValue MwaaPrivateSubnet1
          - !ImportValue MwaaPrivateSubnet2
      WebserverAccessMode: PUBLIC_ONLY
      MaxWorkers: !Ref MaxWorkerNodes
      LoggingConfiguration:
        DagProcessingLogs:
          LogLevel: !Ref DagProcessingLogs
          Enabled: true
        SchedulerLogs:
          LogLevel: !Ref SchedulerLogsLevel
          Enabled: true
        TaskLogs:
          LogLevel: !Ref TaskLogsLevel
          Enabled: true
        WorkerLogs:
          LogLevel: !Ref WorkerLogsLevel
          Enabled: true
        WebserverLogs:
          LogLevel: !Ref WebserverLogsLevel
          Enabled: true

Outputs:
  MwaaApacheAirflowUI:
    Description: MWAA Environment Webserver URL
    Value: !Sub  "https://${MwaaEnvironment.WebserverUrl}"
    