AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  S3BucketName:
    Type: String
    Default: mwaa-airflow-example
    
Resources:
  EnvironmentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  MWAAEnvironmentS3BucketName:
    Description: The S3 bucket created as part of the MWAA build
    Value: !Ref EnvironmentBucket
    Export:
      Name: MWAAEnvironmentS3BucketName
  MWAAEnvironmentS3BucketArn:
    Description: ARN of the S3 bucket created as part of the MWAA build
    Value: !GetAtt EnvironmentBucket.Arn
    Export:
      Name: MWAAEnvironmentS3BucketArn