AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Secrets Manager template

Parameters:
  SecretName:
    Type: String
    Default: example
  SrcSystem:
    Type: String
  engine:
    Description: Type of database engine
    Type: String
  dbname:
    Description: Database name
    Type: String
  host:
    Description: Database hostname to use
    Type: String
  port:
    Description: Port number to use
    Type: String
  username:
    Description: Username to use
    Type: String
  password:
    Description: Password to use
    Type: String
    NoEcho: true

Resources:
  SecretsManagerSecrets:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Ref SecretName
      Description: !Sub 'Database credentials to use for ${SrcSystem} database'
      SecretString: !Sub '{"engine": "${engine}","dbname": "${dbname}","host": "${host}","port": "${port}","username": "${username}","password":  "${password}"}'
