AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Secrets Manager template

Parameters:
  SecretName:
    Type: String
    Default: example
  SrcSystem:
    Type: String
  SecretString:
    Description: The secure connection String
    Type: String
    NoEcho: true

Resources:
  SecretsManagerSecrets:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Ref SecretName
      Description: !Sub 'Database credentials to use for ${SrcSystem} database'
      SecretString: !Ref SecretString
