AWSTemplateFormatVersion: '2010-09-09'

Description: >
  RDS SQL Server Express CFN template.

Parameters:
  DBUser:
    Default: admin
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  InstanceName:
    Default: PF-CFN-RDS-MSSQL-EX-Instance
    Type: String
  DBEngine:
    Default: sqlserver-ex
    Type: String
  DBInstanceType:
    Default: db.t2.micro
    Type: String
  DBEngineVersion:
    Default: 14.00.3223.3.v1
    Type: String
  AllocatedStorage:
    Default: 20
    Type: String
  MyVPC:
    Type: String
    Description: name of the VPC ID to put the RDS instance in
  MyCidrIP:
    Type: String
    Description: My IP address, to be used for creating an RDS instance
  BackupRetentionPeriod:
    Type: String
    Description: The number of days for which automated backups are retained. Setting this parameter to a positive number enables backups. Setting this parameter to 0 disables automated backups
    Default: 0

Resources:
  # Create an RDS instance
  CFNMSSQLExpressDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref AllocatedStorage
      DBInstanceClass: !Ref DBInstanceType
      DBInstanceIdentifier: !Ref InstanceName
      Engine: !Ref DBEngine
      EngineVersion: !Ref DBEngineVersion
      LicenseModel: license-included
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: Yes
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      VPCSecurityGroups:
      - Ref: SecurityGroup

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SG-MSSQL-DB
      GroupDescription: SG for the MSSQL db instance
      VpcId:
        Ref: MyVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 1433
        ToPort: 1433
        CidrIp: !Ref MyCidrIP
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0

Outputs:
  RDSInstanceEP:
    Description: "Hostname / Endpoint of RDMBS instance"
    Value: !GetAtt CFNMSSQLExpressDB.Endpoint.Address
    Export:
      Name: MSSQLDBEndpointAddress