AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Secrets Manager template

Resources:
  SecretsManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: Eg
      GenerateSecretString:
        SecretStringTemplate: '{"username": "eg-user"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
