AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Secrets Manager template for storing RDBMS credentials

Parameters:
  SecretName:
    Type: String
  SrcSystem:
    Type: String
  engine:
    Description: Type of database engine
    Type: String
    AllowedValues:
      - mysql
      - oracle
      - postgres
      - mariadb
      - aurora
      - aurora-postgresql
      - redshift
      - s3
      - db2
      - azuredb
      - sybase
      - dynamodb
      - mongodb
      - kinesis
      - kafka
      - elasticsearch
      - docdb
      - sqlserver
      - neptune
  dbname:
    Description: Database name
    Type: String
  host:
    Description: Database hostname to use
    Type: String
  port:
    Description: Port number to use
    Type: String
  username:
    Description: Username to use
    Type: String
  password:
    Description: Password to use
    Type: String
    NoEcho: true

Resources:
  SecretsManagerSecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Ref SecretName
      Description: !Sub 'Database credentials to use for ${SrcSystem} database'
      SecretString: !Sub '{"engine": "${engine}","dbname": "${dbname}","host": "${host}","port": "${port}","username": "${username}","password":  "${password}"}'
